name = "shopping-list"
pages_build_output_dir = "public"
compatibility_date = "2026-06-04"

[[kv_namespaces]]
binding = "TODO_LIST"
id = "e76453d44bc34b9d91a0eb9e90884512"
preview_id = "e76453d44bc34b9d91a0eb9e90884512"
